name: Emcee Mind
favicon: null
layout_spectrum: 0.7448859217111021
typography_spectrum: 0.11397054977715015
title: EmceeMind.org
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000004'
    - '#aeb6bd'
    - '#636ba5'
    - '#d4dcec'
    - '#3d4166'
  brandStrength: 0.5
  lightness: 0.8815908525139093
  saturation: 0.8376485805492848
  rhythmicContrast: 0.008638626895844936
purpose: []
